# Taller 2

In [ ]:
import numpy as np
notas = np.array([4.3,4.2,1.5,3.5,2.0,2.2,3.5,4.8,5.0,0.0])
print(notas)
# para hallar el promedio de la notas se emplea la funcion np.mean
media = np.mean(notas)
print('media:',media)
# para hallar la desviacion estandar se emplea la funcion np.std
desviacion = np.std(notas)
print('Desviacion Estandar:',desviacion)
# para hallar la mediana estandar se emplea la funcion np.median
mediana = np.median(notas)
print('Mediana:',mediana)
orden = np.sort(notas)
print('Notas ordenadas:', orden)

[4.3 4.2 1.5 3.5 2.  2.2 3.5 4.8 5.  0. ]
media: 3.1
Desviacion Estandar: 1.5381807436059
Mediana: 3.5
Notas ordenadas: [0.  1.5 2.  2.2 3.5 3.5 4.2 4.3 4.8 5. ]


In [ ]:
notas2=np.genfromtxt("Notas.csv",delimiter = ',')
print(notas2)
#hallo el promedio de las notas N1 N2 N3
#print("prueba:\n",notas2[:,1:4])
#n60 = np.mean(notas2[:,1:3])
#print(n60)

#otra opcion
long = np.shape(notas2[:,1:4])
#print(long[1])
prom=np.sum(notas2[:,1:4])/long[1]
print("prueba",prom)

[[ 1.   2.3  0.   0.   0. ]
 [ 2.   2.6  2.7  1.5  1.9]
 [ 3.   2.2  2.   1.5  1.4]
 [ 4.   2.8  2.3  3.   3.2]
 [ 5.   0.   0.   0.   0. ]
 [ 6.   2.8  4.3  3.4  2.9]
 [ 7.   3.3  2.7  3.   3.6]
 [ 8.   3.   2.7  1.5  1. ]
 [ 9.   2.7  2.5  1.   2.8]
 [10.   2.5  2.   2.   1.7]
 [11.   3.8  3.5  1.   2.8]
 [12.   2.5  1.5  1.   2.1]
 [13.   2.7  2.7  1.5  2.6]
 [14.   2.6  4.   1.3  3. ]
 [15.   3.2  1.5  1.5  1. ]
 [16.   0.   2.5  1.8  2.4]
 [17.   4.5  1.8  3.2  3.2]
 [18.   2.7  1.   0.8  1. ]
 [19.   2.2  2.5  1.6  1. ]
 [20.   2.8  0.   1.   1. ]
 [21.   4.1  2.5  2.   2.6]
 [22.   2.7  2.   1.5  2.2]
 [23.   2.   1.   3.3  2.7]
 [24.   3.   2.5  1.   3. ]
 [25.   5.   4.5  5.   4.8]
 [26.   2.6  2.5  1.5  2.3]
 [27.   1.6  1.   1.3  1. ]
 [28.   2.5  1.   2.4  1.7]
 [29.   5.   4.5  2.5  4.3]
 [30.   2.6  2.7  2.   2.2]
 [31.   2.   4.   2.3  4. ]
 [32.   2.8  2.   2.   1.5]]
prueba 72.63333333333334
