# Taller 2

In [ ]:
import numpy as np
notas = np.array([4.3,4.2,1.5,3.5,2.0,2.2,3.5,4.8,5.0,0.0])
print(notas)
# para hallar el promedio de la notas se emplea la funcion np.mean
media = np.mean(notas)
print('media:',media)
# para hallar la desviacion estandar se emplea la funcion np.std
desviacion = np.std(notas)
print('Desviacion Estandar:',desviacion)
# para hallar la mediana estandar se emplea la funcion np.median
mediana = np.median(notas)
print('Mediana:',mediana)
orden = np.sort(notas)
print('Notas ordenadas:', orden)

[4.3 4.2 1.5 3.5 2.  2.2 3.5 4.8 5.  0. ]
media: 3.1
Desviacion Estandar: 1.5381807436059
Mediana: 3.5
Notas ordenadas: [0.  1.5 2.  2.2 3.5 3.5 4.2 4.3 4.8 5. ]


## Punto 1
Investigue como utilizar el comando np.loadtxt o np.genfromtxt para importar datos desde un archivo .csv
a Python, importar los datos del archivo adjunto y calcular: la definitiva de las notas de cada uno de los
estudiantes si se sabe que N1, N2 y N3 se promedian y corresponden al 60 % del corte y el parcial es el
40 %.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
import numpy as np

notas2=np.genfromtxt("Notas.csv",delimiter = ',')
#Tabla de notas
print("tabla de notas:\n",notas2)
#calculo de promedio por notas y calculo de la definitiva
defi=(notas2[:,1:4].mean(axis=1)*0.6)+(notas2[:,4]*0.4)
print("Definitivas por estudiante:\n",defi)

tabla de notas:
 [[ 1.   2.3  0.   0.   0. ]
 [ 2.   2.6  2.7  1.5  1.9]
 [ 3.   2.2  2.   1.5  1.4]
 [ 4.   2.8  2.3  3.   3.2]
 [ 5.   0.   0.   0.   0. ]
 [ 6.   2.8  4.3  3.4  2.9]
 [ 7.   3.3  2.7  3.   3.6]
 [ 8.   3.   2.7  1.5  1. ]
 [ 9.   2.7  2.5  1.   2.8]
 [10.   2.5  2.   2.   1.7]
 [11.   3.8  3.5  1.   2.8]
 [12.   2.5  1.5  1.   2.1]
 [13.   2.7  2.7  1.5  2.6]
 [14.   2.6  4.   1.3  3. ]
 [15.   3.2  1.5  1.5  1. ]
 [16.   0.   2.5  1.8  2.4]
 [17.   4.5  1.8  3.2  3.2]
 [18.   2.7  1.   0.8  1. ]
 [19.   2.2  2.5  1.6  1. ]
 [20.   2.8  0.   1.   1. ]
 [21.   4.1  2.5  2.   2.6]
 [22.   2.7  2.   1.5  2.2]
 [23.   2.   1.   3.3  2.7]
 [24.   3.   2.5  1.   3. ]
 [25.   5.   4.5  5.   4.8]
 [26.   2.6  2.5  1.5  2.3]
 [27.   1.6  1.   1.3  1. ]
 [28.   2.5  1.   2.4  1.7]
 [29.   5.   4.5  2.5  4.3]
 [30.   2.6  2.7  2.   2.2]
 [31.   2.   4.   2.3  4. ]
 [32.   2.8  2.   2.   1.5]]
Definitivas por estudiante:
 [0.46 2.12 1.7  2.9  0.   3.26 3.24 1.84 2.36 1.98 2.78 1

## Punto 2
Encuentre la media, la desviación estándar y la mediana (recuerde que para este dato los números tiene
que estar ordenados de forma creciente) de las notas definitivas.

In [ ]:
import numpy as np
#Media
print("Media definitivas:",round(np.mean(defi),2))
#desviacion estandar
print("Desviacion estandar definitivas:",round(np.std(defi),2))
#Mediana
orden=np.sort(defi)
print("Definitivas ordenadas",orden)
print("Mediana definitivas:",round(np.median(defi),2))

Media definitivas: 2.25
Desviacion estandar definitivas: 0.95
Definitivas ordenadas [0.   0.46 1.16 1.18 1.3  1.64 1.66 1.7  1.82 1.84 1.84 1.86 1.96 1.98
 2.12 2.12 2.24 2.34 2.34 2.36 2.42 2.5  2.76 2.78 2.78 2.9  3.18 3.24
 3.26 3.26 4.12 4.82]
Mediana definitivas: 2.18


## Punto 3

Hay tres estudiantes que estaban en el grupo de otro profesor y cuyas notas son:
|est|N1|N2|N3|PARCIAL|
|---|---|---|---|---|
|33|4.3|2.3|1.5|3.7|
|34|4.2|3.1|2.0|4.0|
|35|1.5|2.8|3.8|3.1|

Calcule la nota definitiva de cada uno, concatene los datos con los cargados anteriormente haciendo uso
de python y calcule de nuevo la media, la mediana y la desviación estándar. Puede ser util el comando
np.concatenate o np.vstack


In [ ]:
import numpy as np
notas3=np.array([[33,4.3,2.3,1.5,3.7],[34,4.2,3.1,2.0,4.0],[35,1.5,2.8,3.8,3.1]])
#Concatenar notas
notas4=np.concatenate((notas2,notas3),axis=0)
#Calcular definitivas
defi2=(notas4[:,1:4].mean(axis=1)*0.6)+(notas4[:,4]*0.4)
print(defi2)
#Media
print("Media definitivas:",round(np.mean(defi2),2))
#desviacion estandar
print("Desviacion estandar definitivas:",round(np.std(defi2),2))
#Mediana
orden2=np.sort(defi2)
print("Definitivas ordenadas",orden2)
print("Mediana definitivas:",round(np.median(defi2),2))

[0.46 2.12 1.7  2.9  0.   3.26 3.24 1.84 2.36 1.98 2.78 1.84 2.42 2.78
 1.64 1.82 3.18 1.3  1.66 1.16 2.76 2.12 2.34 2.5  4.82 2.24 1.18 1.86
 4.12 2.34 3.26 1.96 3.1  3.46 2.86]
Media definitivas: 2.32
Desviacion estandar definitivas: 0.94
Definitivas ordenadas [0.   0.46 1.16 1.18 1.3  1.64 1.66 1.7  1.82 1.84 1.84 1.86 1.96 1.98
 2.12 2.12 2.24 2.34 2.34 2.36 2.42 2.5  2.76 2.78 2.78 2.86 2.9  3.1
 3.18 3.24 3.26 3.26 3.46 4.12 4.82]
Mediana definitivas: 2.34
